AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10
